#DataSource Configuration
spring:
  datasource:
    driver-class-name:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true


